export const HANDLECHANGETEXT = 'HANDLECHANGETEXT';
export const HANDLEPICKER = 'HANDLEPICKER';
export const FILTERCOMPLETEDITEMS = 'FILTERCOMPLETEDITEMS';
export const FILTERACTIVEITEMS = 'FILTERACTIVEITEMS';
export const ADDTOLIST = 'ADDTOLIST';
export const REMOVEFROMLIST = 'REMOVEFROMLIST';

export const SHOWPICKERINITEM = 'SHOWPICKERINITEM';
export const HIDEPICKERINITEM = 'HIDEPICKERINITEM';
export const TOGGLETEXTINPUT = 'TOGGLETEXTINPUT';
export const EDITITEMTEXT = 'EDITITEMTEXT';
export const EDITITEMDATE = 'EDITITEMDATE';
export const EDITITEMSTATUS = 'EDITITEMSTATUS';

